(require 2htdp/image)
;; Image -> Image
;; (define (outline i) )
;; (define (outline i)
;;   (...i))
(check-expect (outline(circle 30 "solid" "blue"))
              (overlay(rectangle 60 60 "outline" "black")
                      (circle 30 "solid" "blue")))
(check-expect (outline(rectangle 30 40 "solid" "purple"))
              (overlay(rectangle 30 40 "outline" "black")
                      (rectangle 30 40 "solid" "purple")))
(define(outline i)
  (overlay(rectangle (image-width i) (image-height i) "outline" "black")
        i))
